theme: jekyll-theme-cayman
plugins: 
- jekyll-github-metadata
- jekyll-titles-from-headings
title: 'Sourcegraph & OSS'
description: 'The benefits of Sourcegraph in OSS'
github:
 is_project_page: false
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
